### ISSUE TITLE
Problems with configuring workload identity on existing cluster

### ISSUE THREAD

**Issue by WilliamHZ** [GoogleCloudPlatform/cloud-sql-proxy#1006]
## Description
I have tried to deploy a Cloud SQL proxy on existing cluster with Workload identity, but Cloud SQL API is disabled in Cloud nodes pool. 
## Solution
If u already created a cluster and u have the default service account so cloud sql api is not enable there - so workload identity will never works with this instances.

**Comment by enocom** [comment]
@WilliamHZ did you see the documentation here? https://github.com/GoogleCloudPlatform/cloudsql-proxy/tree/main/examples/k8s-sidecar#workload-identity

Trying to figure out what we might do differently.

**Comment by WilliamHZ** [comment]
@enocom Yes, I tired to set up a proxy and followed the documentations https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine#service-account-key and https://github.com/GoogleCloudPlatform/cloudsql-proxy/tree/main/examples/k8s-sidecar#setting-up-a-service-account
But it doesn't work on an existing cluster.

**Comment by enocom** [comment]
What error are you getting when the Proxy tries to connect?

Also, have you tried verifying your setup? Step 9 here shows you how to run a test on a pod: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to

**Comment by WilliamHZ** [comment]
Error: 
the default Compute Engine service account is not configured with sufficient permissions to access the Cloud SQL API from this VM. Please create a new VM with Cloud SQL access (scope) enabled under "Identity and API access". Alternatively, create a new "service account key" and specify it using the -credential_file parameter

**Comment by enocom** [comment]
That error looks like you're not using the workload identity.

If you create a test like so:

``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: workload-identity-test
  namespace: default
spec:
  containers:
  - image: google/cloud-sdk:slim
    name: workload-identity-test
    command: ["sleep","infinity"]
  serviceAccountName: KSA_NAME
```

And apply it:

```
kubectl apply -f wi-test.yaml
```

And then run:

```
kubectl exec -it workload-identity-test --namespace YOUR_NAMESPACE -- /bin/bash
```

And finally:

```
curl -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/service-accounts/
```

Do you see the service account you've configured for workload identity?
