### ISSUE TITLE
Intermittent connectivity issues from node app in kubernetes sidecar deployment

### ISSUE THREAD

**Issue by rigratz** [GoogleCloudPlatform/cloud-sql-proxy#1316]
Hello, I've been attempting to run down a connectivity issue with a handful of different Google reps, and they suggested I create an issue here so that it can be tracked easily.

## Bug Description
I have two kubernetes applications running on GKE v1.22 that connects to a cloud SQL db using a Kubernetes sidecar container as described in Google's documentation. One of these applications works fine. The other one however, runs into an issue roughly every 24 hours where connectivity is temporarily lost, as the logs appear to show the Cloud SQL Auth Proxy throwing an error and restarting. The error message logged is extremely vague so I'm not sure entirely what is at fault, but it is very interesting that this is only impacting one of the services even though their sidecar configurations are identical. During the time that the proxy is restarting, the application is down and unable to handle requests, which is obviously a big problem.

## Example code (or command)
Pods are being managed as part of `Deployment` resources, and the relevant configuration looks something like this (irrelevant details omitted). This configuration was done in accordance with the documentation and sample apps described here: https://cloud.google.com/sql/docs/sqlserver/connect-kubernetes-engine#run_the_as_a_sidecar:

```
apiVersion: apps/v1
kind: Deployment
...
spec:
  ...
  template:
    ...
    spec:
      containers:
      - command:
        - /cloud_sql_proxy
        - -instances=REDACTED=tcp:1433
        image: gcr.io/cloudsql-docker/gce-proxy:1.31.0
        imagePullPolicy: IfNotPresent
        name: cloud-sql-proxy
        resources: {}
        securityContext:
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - envFrom:
        - secretRef:
            name: REDACTED # Credentials to the DB come from here
        image: REDACTED
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /ping
            port: 80
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: REDACTED
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: REDACTED
      serviceAccountName: REDACTED
      terminationGracePeriodSeconds: 30
```

## Stacktrace
Logs from Cloud SQL proxy, which correlate with logs from our service being unable to connect to sql, and the proxy then restarting:
```
Get "https://sqladmin.googleapis.com/sql/v1beta4/projects/OUR-SQL-INSTANCE/connectSettings?alt=json&prettyPrint=false": dial tcp: lookup sqladmin.googleapis.com on 10.3.240.10:53: read udp 10.0.15.4:45428->10.3.240.10:53: read: connection refused

errors parsing config:
```
...without information on what config was wrong or why (NOTE: those IPs are not our databse, but I assume you'll know what they are)

## How to reproduce

  1. We deploy our application using a Helm chart and FluxCD. This creates the deployments which spin up the pods
  2. Monitor logs and ~24 hours apart from each other there will be daily disconnection errors (FWIW this has currently been happening around 530 AM PST)

## Environment

1. OS type and version: Base docker image is node:14-alpine (Alpine Linux)
2. Cloud SQL Proxy version (`./cloud_sql_proxy -version`): gcr.io/cloudsql-docker/gce-proxy:1.31.0
