### ISSUE TITLE
Proxy exits with wrong code after SIGTERM

### ISSUE THREAD

**Issue by cdaguerre** [GoogleCloudPlatform/cloud-sql-proxy#1529]
## Bug Description

Graceful termination seems impossible in v2. Whether I set `--max-sigterm-delay` or not doesn't matter, process always has exit code `137`, even when there are no active connections.

## Example code (or command)

```yaml
- name: cloudsql-proxy
  image: {{ $root.Values.sqlProxy.image }}
  command:
    - '/kubexit/kubexit'
    - '/cloud-sql-proxy'
    - '--address=127.0.0.1'
    - '--max-sigterm-delay=10s'
    - '--structured-logs'
    - '--prometheus'
    {{- range $k, $v := $root.Values.sqlProxy.connections }}
    - '{{ $v.dsn }}?port={{ $v.port }}'
    {{- end }}
  lifecycle:
    preStop:
      exec:
        command: ['sleep', '10']
```

## Stacktrace

<img width="1439" alt="Capture d’écran 2022-11-05 à 18 05 03" src="https://user-images.githubusercontent.com/4642448/200132371-581759da-5632-4d97-848b-bbff0c875cf4.png">

## How to reproduce

  1. ?
  2. ?

## Environment

1. OS type and version: GKE 1.24.4-gke.800
2. Cloud SQL Proxy version (`./cloud-sql-proxy --version`): 2.0.0-preview.2
