### ISSUE TITLE
Docker image gce-proxy:1.33.3-alpine is missing libraries

### ISSUE THREAD

**Issue by tun0** [GoogleCloudPlatform/cloud-sql-proxy#1678]
### Bug Description

The Alpine version of the latest gce-proxy image is lacking some libraries, making it unable to run `/cloud_sql_proxy`:

```
Error loading shared library libresolv.so.2: No such file or directory (needed by /cloud_sql_proxy)
Error relocating /cloud_sql_proxy: __res_search: symbol not found
```

### Example code (or command)

```
// paste your code or command here
```

### Steps to reproduce?

1. Run: `docker run -it --rm eu.gcr.io/cloudsql-docker/gce-proxy:1.33.3-alpine /cloud_sql_proxy`
2. Expect:
```
2023/02/23 07:04:20 current FDs rlimit set to 1073741816, wanted limit is 8500. Nothing to do here.
2023/02/23 07:04:20 gcloud is not in the path and -instances and -projects are empty
```
Actual result:
```
Error loading shared library libresolv.so.2: No such file or directory (needed by /cloud_sql_proxy)
Error relocating /cloud_sql_proxy: __res_search: symbol not found
```

### Environment

1. OS type and version: GKE 1.25 and latest Manjaro
2. Cloud SQL Proxy version (`./cloud-sql-proxy --version`): 1.33.3
3. Proxy invocation command (for example, `./cloud-sql-proxy --enable_iam_login --dir /path/to/dir INSTANCE_CONNECTION_NAME`): just plain `/cloud_sql_proxy` without any parameters

**Comment by GroundedBeans** [comment]
Same issue seems to affect the 2.1.0 alpine image (eu.gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0-alpine). 
Distroless (default) 2.1.0 image does not suffer from the same issue.

**Environment**

- OS type and version: GKE 1.23
- Cloud SQL Proxy image: 2.1.0-alpine
- Proxy kubernetes definition:
```
containers:    
  - name: cloudsql-proxy
    image: eu.gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0-alpine
    args:
      - "--structured-logs"
      - "--port=1433"
      - "--private-ip"
      - "<INSTANCE_URL>"
 .
 .
 .
```

**GKE logs** 
```
Error loading shared library libresolv.so.2: No such file or directory (needed by /cloud-sql-proxy)
Error relocating /cloud-sql-proxy: __res_search: symbol not found
```
