### ISSUE TITLE
Logs not structured when both `--structured-logs` and `--quiet` are used together

### ISSUE THREAD

**Issue by kaiburjack** [GoogleCloudPlatform/cloud-sql-proxy#1738]
### Bug Description

In an attempt to identify log entries that are _actual_ errors and reduce noise from log entries which aren't, but are detected as such by the default fluentbit log agent (and thus by GCP Logging Explorer) because they are written text form to the POSIX STDERR stream, we tried to configure the Google Cloud Sql Proxy using both:

- `--structured-logs` (in order to help fluentbit/stackdriver to detect _actual_ errors and not flag text output as errors because it was printed to STDERR)
- `--quiet` (because all those "certificate expires, getting a new one..." or "client opened a new connection..." wasn't giving us much information and we tried to lower the overall logging storage costs.)

However, everytime the cloud sql proxy container gets terminated (because of a simple scaledown of the pod it is living in), we noticed the unstructured log output (to STDERR): `SIGTERM signal received. Shutting down...` which is coming from https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/6284a69342c87190e5201865de447b54da55d798/cmd/root.go#L840 

First: This is _arguably_ not an error.
Second: This is also not structured, because whenever `--structured-logs` is used together with `--quiet`, the structured logger is again replaced by the NewStdLogger, as can be seen in this code section: https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/6284a69342c87190e5201865de447b54da55d798/cmd/root.go#L344-L349 

It would be nice, if both:
- `SIGTERM signal received. Shutting down...` would not be logged/treated as an _error_ (maybe a _warning_)
- using structured-logs together with quiet would not disable structured logging

### Steps to reproduce?

Run cloudsql proxy with both `--structured-logs` and `--quiet` and issue a SIGTERM signal (as is used in Kubernetes) to stop it.

### Environment

1. OS type and version: Standard GKE 1.25 Linux OS with containerd
2. Cloud SQL Proxy version (`./cloud-sql-proxy --version`): 2.1.2
3. Proxy invocation command (for example, `./cloud-sql-proxy --enable_iam_login --dir /path/to/dir INSTANCE_CONNECTION_NAME`):
```yaml
        - name: cloud-sql-proxy
          image: eu.gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.2-alpine
          args:
            - "--private-ip"
            - "--quiet"
            - "--structured-logs"
            - "--health-check"
            - "--http-port=9090"
            - "--max-sigterm-delay=15s"
            - "--port=5432"
            - "..."
```
