### ISSUE TITLE
gce-proxy:1.33.6 -> cloud-sql-proxy:2.2.0 failing

### ISSUE THREAD

**Issue by dudo** [GoogleCloudPlatform/cloud-sql-proxy#1769]
### Bug Description

I have a working cloud-sql-proxy k8s sidecar that I setup last year per [the docs](https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine#run_the_in_a_sidecar_pattern). I used `gcr.io/cloudsql-docker/gce-proxy:1.33.6` at the time. Upon checking the docs for something related, I saw that the recommended image is `gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.2.0`.

While attempting to update, my app can't connect - responding with `ECONNREFUSED`.

I reverted the changes, and it connects, so the problem seems isolated.

Might be related, but the "app" in this case is a database migration running within a k8s Job - it's small, and quite quick. Even before updating, I'd occasionally have to try the job a time or two before it would connect. I never really thought anything of it, because it would work after kicking it a few times. This problem may be exacerbated with the new image?

### Example code (or command)

![Screenshot 2023-04-24 at 21 56 58](https://user-images.githubusercontent.com/2963800/234178436-db69b782-36d4-4107-823c-5c997fe2da50.png)

### Steps to reproduce?

1. swapped gce-proxy for cloud-sql-proxy (per newer docs)
2. updated command accordingly

### Environment

see picture

**Comment by dudo** [comment]
The proxy isn't giving me any logs, unfortunately... 

```sh
[library-service] k logs library-service-migrations-dcb6h -c migrations                                                                                                
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
}
[library-service] k logs library-service-migrations-dcb6h -c cloud-sql-proxy  

```

The Job events don't tell a story, either

```sh
Events:
  Type    Reason            Age    From            Message
  ----    ------            ----   ----            -------
  Normal  SuccessfulCreate  5m32s  job-controller  Created pod: library-service-migrations-dcb6h
  Normal  SuccessfulCreate  2m38s  job-controller  Created pod: library-service-migrations-7n6nq
  Normal  SuccessfulCreate  2m10s  job-controller  Created pod: library-service-migrations-kzkqw
  Normal  SuccessfulCreate  93s    job-controller  Created pod: library-service-migrations-sch9t
  Normal  SuccessfulCreate  36s    job-controller  Created pod: library-service-migrations-7g6wx
```

Interestingly, the new image allows the Job to fail, and retry, whereas the previous image would just hang if it failed. Not sure if that can shed any light here.

**Comment by dudo** [comment]
I'm not using private IPs. Note the original image with its flags, and that it connected correctly. That being said I tried with the private flag with the same results.

Applying this yaml...

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: library-service-migrations
spec:
  backoffLimit: 4
  template:
    spec:
      serviceAccountName: library-service
      restartPolicy: Never
      imagePullSecrets:
        - name: registry-auth
      containers:
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.2.0
          imagePullPolicy: IfNotPresent
          command:
            - "--structured-logs"
            - "--port=5432"
            - "my-project-123456:us-west1:my-db"
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
```

results in...

```sh
library-service-migrations-2tn8b             0/1     Pending             0             0s
library-service-migrations-2tn8b             0/1     ContainerCreating   0             0s
library-service-migrations-2tn8b             0/1     StartError          0             3s
```

with no log output... 

Is the service account setup between the old image and the new? Looks the same... I don't think that's the culprit. Is my `INSTANCE_CONNECTION_NAME` correct?

**Comment by enocom** [comment]
Looks perfectly correct to me. And just in case, I ran the same command locally with the same container and could connect with `psql`.

Have you tried running the Proxy in a simple deployment by comparison? Do you have any other workloads running the Proxy without issue?

**Comment by dudo** [comment]
I have my Deployments running with the previous proxy image. Was testing out the new one with the Job because it's just easier, lol. I can try with a Deployment if you think it'd help debug, but I'm doubtful.

What could be different between the previous image and this one? For posterity,I'm using GKE on Autopilot, and Cloud SQL Postgres. Let's do some updates...

- GKE
  - build `1.24.10-gke.2300`
  - updating to `1.25.7-gke.1000`
    - same error
  - updating to `1.26.2-gke.1000`
    - same error
- SQL
  - build `14.4`
  - updating to `14.5`
    - same error

**Comment by dudo** [comment]
We're getting closer! The Deployment was a touch more helpful. Still no logs, but this time describing the pod captured something.

```sh
proxy-test-7d4b9bd87d-6qvnd                  0/1     Pending   0            0s
proxy-test-7d4b9bd87d-6qvnd                  0/1     Pending   0            0s
proxy-test-7d4b9bd87d-6qvnd                  0/1     ContainerCreating   0            0s
proxy-test-7d4b9bd87d-6qvnd                  0/1     RunContainerError   0 (0s ago)   3s
```

```yaml
    Last State:     Terminated
      Reason:       StartError
      Message:      failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "--structured-logs": executable file not found in $PATH: unknown
```

**Comment by enocom** [comment]
Would you mind sharing the deployment yaml for reference? That looks like a faulty invocation.

**Comment by dudo** [comment]
This was copied from here

<img width="680" alt="Screenshot 2023-05-02 at 10 17 00" src="https://user-images.githubusercontent.com/2963800/235737830-f60cf2de-d56b-4450-a34c-c8f2a911dfd4.png">

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: proxy-test
spec:
  selector:
    matchLabels:
      app: proxy-test
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: proxy-test
    spec:
      serviceAccountName: library-service
      restartPolicy: Always
      imagePullSecrets:
        - name: registry-auth
      containers:
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.2.0
          imagePullPolicy: IfNotPresent
          command:
            - "--structured-logs"
            - "--port=5432"
            - "kinetic-dryad-364616:us-west1:mono-db"
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              memory: 500M
              cpu: 500m
            limits:
              memory: 1G
              cpu: 1000m

```
