### ISSUE TITLE
failed to connect to instance: Dial error: failed to dial

### ISSUE THREAD

**Issue by Swahjak** [GoogleCloudPlatform/cloud-sql-proxy#1840]
### Bug Description

Since we've upgraded from 1.\*.\* to 2.\*.\* we have been noticing 'a lot' of "failed to connect to instance: Dial error: failed to dial (connection name = "\*\*\*\*\*\*"): dial tcp \*\*.\*\*\*.\*\*\*.\*\*:3307: i/o timeout" errors in the SQL Proxy container. We have been trying to debug this issue, but there doesn't really seem to be a clear explanation for it. It is happening across multiple (PHP) applications using different frameworks. Downgrading back to 1.\*.\* seems to resolve the issue, which (I think) rules out that it is network related. The database is not under (very) heavy load and we're only using ~5% of our connections limit.

### Example code (or command)

```
...
      - command:
        - /cloud-sql-proxy
        - --health-check
        - --http-address=0.0.0.0
        - --credentials-file=/secrets/cloudsql/cloudsqlproxy-credentials.json
        - --max-sigterm-delay=60s
        - --structured-logs
        - --quiet
        - toppy-***:europe-west4:toppy-***-database
        image: eu.gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.2.0
        imagePullPolicy: IfNotPresent
        name: cloudsqlproxy-container
        ports:
        - containerPort: 3306
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: true
          privileged: false
          readOnlyRootFilesystem: false
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
        startupProbe:
          failureThreshold: 20
          httpGet:
            path: /startup
            port: 9090
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets/cloudsql
          mountPropagation: None
          name: cloudsqlproxy-service-account
          readOnly: true
...
```

### Stacktrace

```bash
n/a
```

### Steps to reproduce?

1. Not sure, included the sidecar yaml

### Environment

1. OS type and version: GKE 1.25.8-gke.500, Container-Optimized OS with containerd (cos_containerd)
2. Cloud SQL Proxy version (`./cloud-sql-proxy --version`): 2.2.0
3. Proxy invocation command (for example, `./cloud-sql-proxy --port 5432 INSTANCE_CONNECTION_NAME`): `/cloud-sql-prox --health-check --http-address=0.0.0.0 --credentials-file=/secrets/cloudsql/cloudsqlproxy-credentials.json --max-sigterm-delay=60s --structured-logs --quiet toppy-***:europe-west4:toppy-***-database`

### Additional Details

- Connection is made over a public IP

Edit: updated yaml

**Comment by jackwotherspoon** [comment]
@Swahjak Thanks for raising an issue on the Cloud SQL Proxy 😄 

handing this over to @hessjcg who is our GKE specialist, he should be able to shed some light on this and hopefully help you get to the bottom of additional errors being seen.

**Comment by enocom** [comment]
This is surprising. 

What region do your GKE nodes live in compared to your instance?

**Comment by Swahjak** [comment]
CloudSQL is in europe-west4-b and GKE in europe-west4-a

**Comment by Swahjak** [comment]
Downgrading to 1.x.x does seem to reduce the amount of error messages, but we are still seeing `couldn't connect to "toppy-***:europe-west4:toppy-***-database": dial tcp 35.2**.2**.2**:3307: connect: connection timed out` every now and then (different message, but I assume it's the same issue).

![Screenshot from 2023-06-14 17-34-06](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/assets/4386577/bbd703a0-f09e-4e0d-9b16-5b17dba40795)
Screenshot from error reporting on one of our applications where we returned to 1.23.x **without** healthchecks, patched at ~12:30

![Screenshot from 2023-06-14 17-33-46](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/assets/4386577/76d47784-e4cd-482d-8353-c33f9386d611)
Screenshot from error reporting on one of our applications where we returned to 1.33.x **with** healthchecks, patched at ~16:30

We're seeing the same results in the cloud-sql-proxy logs, where the amount of errors seems to align with the errors reported by the applications.

**Comment by enocom** [comment]
Normally i/o timeout errors indicate no network path from the Proxy to the instance. Assuming there are no changes in your environment to limit access to your public IP, I see one thing that might be worth trying: the resource limits are smaller than we usually recommend.

Compare:

``` 
resources:  
  requests:
    cpu: 100m
    memory: 100Mi
```

vs (what [we recommend as a starting point](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/examples/k8s-sidecar/proxy_with_workload_identity.yaml#LL78C1-L87C24)):

```
resources:
  requests:
    # The proxy's memory use scales linearly with the number of active
    # connections. Fewer open connections will use less memory. Adjust
    # this value based on your application's requirements.
    memory: "2Gi"
    # The proxy's CPU use scales linearly with the amount of IO between
    # the database and the application. Adjust this value based on your
    # application's requirements.
    cpu:    "1"
```

I'd suggest starting with these large values and then adjusting based on observed usage. This could be a case of CPU throttling.

**Comment by enocom** [comment]
All good points. I'm wondering if the healthcheck in v2 is causing the difference.

**Comment by RossAddinall** [comment]
@Swahjak thanks so much for posting this issue.  I've been tearing my hair out trying to figure what I am doing wrong (and maybe I am still doing something wrong), but I am getting exactly the same message as you.  I am setting up a new Kubernetes cluster from scratch and this is my first time hooking up to Cloud SQL, so I have no history to compare against.

I want to test by dropping back to the earlier version, what is the image you are using for the 1.x.x? so I can give it a go.

I have tried:
```
image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:1.33.7
```
and 
```
image: gcr.io/cloud-sql-docker/gce-proxy:1.33.7
```
but in each case I get image pull failures

Also, just a quick dumb question, but just to be sure, when I connect to the database, the name I pass is the name of a database on the database instance and not the name of the database instance?  and I can connect on the standard port and using ```localhost```, I've tried both ```localhost``` and ```127.0.0.1```, I just want to make sure I've not made a silly snafu.

The Google docs are always just a little light on some of these more basic details.

Many thanks,
Ross

**Comment by RossAddinall** [comment]
Oh, I should also have said, I am using the default sidecar configuration as described in the Google docs [here](https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine#run_the_in_a_sidecar_pattern), so I have the recommended resources.

**Comment by jackwotherspoon** [comment]
@RossAddinall the image pull issue is because you have a slight typo in your second attempt. (`cloudsql-docker` instead of `cloud-sql-docker`)

The v1 image should work with the following:
```
image: gcr.io/cloudsql-docker/gce-proxy:1.33.7
```

> when I connect to the database, the name I pass is the name of a database on the database instance and not the name of the database instance?

Are you referring to the `INSTANCE_CONNECTION_NAME`? 

The `INSTANCE_CONNECTION_NAME` for your instance can be found on the **Overview** page for your instance in the [Google Cloud console](https://console.cloud.google.com/sql) or by running the following command:

```sh
gcloud sql instances describe <INSTANCE_NAME> --format='value(connectionName)'
```
Where `INSTANCE_NAME` is the name of your Cloud SQL instance.

If you are referring to `DB_NAME` when connecting that is the name of the actual database on the instance itself and not the instance name.

> I can connect on the standard port and using `localhost`, I've tried both `localhost` and `127.0.0.1`?

Yes both `localhost` and `127.0.0.1` should work for connections. Although we normally recommend `127.0.0.1`.

Hope this helps clarify.

**Comment by RossAddinall** [comment]
@jackwotherspoon many thanks for your help, in fact it turns out that it was my mistake, if you don't mind I'll document here what I did.

#### TLDR is:
The Cloud SQL proxy is attempting to connect to the Public IP address of the Cloud SQL instance.  I was unable to get to that IP from my container and edited my egress NAT policy following [this](https://cloud.google.com/kubernetes-engine/docs/how-to/egress-nat-policy-ip-masq-autopilot).  Once I added a CIDR for the Cloud SQL Public IP address (x.x.x.0/24), things started working (afaik).

#### Answers to @jackwotherspoon question:
I was actually referring to the DB_NAME and I was using the name of a database running on the database instance, though not initially!

#### Longer version:
This is what I did after the input from @jackwotherspoon:
1. Corrected the typo in the image I was pulling for the Cloud SQL proxy.  When ```kubectl apply```ing the deployment I got CrashLoopBackOff errors, this is because the 1.x.x image appears to look for a ```command:```, instead of an ```args:``` entry.  I spotted this [in this video](https://www.youtube.com/watch?v=CNnzbNQgyzo) and this is what I used:

```yaml
image: gcr.io/cloudsql-docker/gce-proxy:1.33.7
command:
  - /cloud_sql_proxy
  - '-instances=<INSTANCE_CONNECTION_NAME>=tcp:5432'
```

when this finally ran I got an error message:
```
2023/06/15 13:33:20 current FDs rlimit set to 1048576, wanted limit is 8500. Nothing to do here.
2023/06/15 13:33:21 Listening on 127.0.0.1:5432 for xxx
2023/06/15 13:33:21 Ready for new connections
2023/06/15 13:33:21 Generated RSA key in 295.212694ms
2023/06/15 13:33:30 New connection for "xxx"
2023/06/15 13:33:30 refreshing ephemeral certificate for instance xxx
2023/06/15 13:33:30 Scheduling refresh of ephemeral certificate in 54m59s
2023/06/15 13:35:42 couldn't connect to "xxx": dial tcp x.x.x.x:3307: connect: connection timed out
```

this convinced me (more than the 2.x.x output), that this was a connectivity issue.  It was also at this point that I realised that the IP address was the public IP of the Cloud SQL instance, which I hadn't grokked previously.

I then switched back to version 2.3.0 and when I remembered to also switch to the ```args``` format, that all worked as well - so far.

I wanted to know if I could get to that IP from my container, so I did:
```
kubectl exec deployment-7744bdb78b-d74dl  -i -t -- bash -il
```
I can't use ping in my container so I used:
```
wget -T 30 x.x.x.x:3307
```
and observed that it timed out.

I then decided I needed to configure my egress.

I looked at [this](https://rajathithanrajasekar.medium.com/google-cloud-public-gke-clusters-egress-traffic-via-cloud-nat-for-ip-whitelisting-7fdc5656284a) which then lead me to [this](https://cloud.google.com/kubernetes-engine/docs/how-to/egress-nat-policy-ip-masq-autopilot).

I created an egress-nat-policy.yaml as described in that final document and I defined a CIDR for x.x.x.0/24 and applied it to my cluster:
```
kubectl apply -f egress-nat-policy.yaml
```
At this point the ```wget``` failed instantly with ```error getting response```

And my container started correctly and connected to the database.
