### ISSUE TITLE
Brief summary of what bug or error was observed

### ISSUE THREAD

**Issue by runephilosof-karnovgroup** [GoogleCloudPlatform/cloud-sql-proxy#1841]
### Bug Description

The error message says port `3307`, but I have specified port `5432`.

The output from sql proxy
```
Listening on 127.0.0.1:5432
accepted connection from 127.0.0.1:58436
failed to connect to instance: Dial error: failed to dial (connection name = "xxx"): dial tcp x.x.x.x:3307: i/o timeout
```

### Example code (or command)

From my deployment
```
      - image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.3.0
        name: cloud-sql-proxy
        args:
          - "--private-ip"
          - "--structured-logs"
          - "--port=5432"
          - "--credentials-file=/secrets/credentials.json"
          - "xxx"
        securityContext:
          runAsNonRoot: true
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/
            readOnly: true
```

### Steps to reproduce?

1. Deploy it as a sidecar configured with port 5432, pointing at a server it cannot reach.
2. Connect to it.
3. Wait for the timeout
...

### Environment

See the example code for the environment
