### ISSUE TITLE
Enabling prometheus with proxy container

### ISSUE THREAD

**Issue by bchkhaidze** [GoogleCloudPlatform/cloud-sql-proxy#1857]
### Question

Hello,
I'm trying to enable prometheus on a cloud sql auth proxy container but I cant access it.
I've tried different ports but without success. In prometheus I see an error: 
**Get "http://x.x.x.x:9090/metrics": dial tcp x.x.x.x:9090: connect: connection refused**
I don't see in documentation anything about promethues metrics port.
Here is a simplified manifest of my pod.
Can you please tell what am I missing here?

### Code

```Go
apiVersion: v1
kind: Pod
metadata:
  name: pgbouncer-pod
  namespace: test
  spec:
    containers:
    - name: pgbouncer
      image: bitnami/pgbouncer:1.19.1
      ports:
        - name: pgbouncer
          containerPort: 5432
          protocol: TCP
    - name: cloud-sql-auth-proxy
      image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.3.0
      args:
        - '--auto-iam-authn'
        - '--structured-logs'
        - '--private-ip'
        - '--max-sigterm-delay=30s'
        - '--prometheus'
        - '--port=5431'
        - $(INSTANCES)
      ports:
        - name: metrics
          containerPort: 9090
          protocol: TCP
      env:
        - name: INSTANCES
          value: some_test_instance
```

**Comment by bchkhaidze** [comment]
I was able to resolve an issue.
Actually there are flags to configure http server address and port for metrics.
--http-address string                  Address for Prometheus and health check server (default "localhost")
--http-port string                     Port for Prometheus and health check server (default "9090")
I was leaving --http-address to default value - localhost, which wasn't working so I added "--http-address=0.0.0.0"
Changing my manifest like this helped
```
apiVersion: v1
kind: Pod
metadata:
  name: pgbouncer-pod
  namespace: test
  spec:
    containers:
    - name: pgbouncer
      image: bitnami/pgbouncer:1.19.1
      ports:
        - name: pgbouncer
          containerPort: 5432
          protocol: TCP
    - name: cloud-sql-auth-proxy
      image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.3.0
        args: 
          - "--auto-iam-authn"
          - "--structured-logs"
          - "--private-ip"
          - "--max-sigterm-delay=30s"
          - "--prometheus"
          - "--http-address=0.0.0.0"
          - "--http-port=9090"
          - "--port=5431"
          - "$(INSTANCES)"
      ports:
        - name: metrics
          containerPort: 9090
          protocol: TCP
      env:
        - name: INSTANCES
          value: some_test_instance
```
