### ISSUE TITLE
How to use v2 Proxy with GitHub Actions

### ISSUE THREAD

**Issue by kopax-polyconseil** [GoogleCloudPlatform/cloud-sql-proxy#1989]
### Question

Read important edit below.

What is the difference between `cloud-sql-proxy` and `cloud_sql_proxy` ?

**EDIT**

I just understood `cloud_sql_proxy` is v1, and `cloud-sql-proxy` is v2.

However, v1 does not have issue to work with github action [`google-github-actions/auth@v1`](https://github.com/google-github-actions/auth), while v2 use a wrong project `application-default`, and seems to need long live credentials.

We used the v1 as it seems better. Did we miss something ?

### Additional Details

After reading your documentation on how to send SQL queries non interfactive, I have been struggling configuring  `cloud-sql-proxy` in a github action.  

This is the documentation : https://cloud.google.com/sql/docs/mysql/connect-auth-proxy

This is the URL advised on the documentation for the cloud sql proxy binary :  https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.7.0/cloud-sql-proxy.linux.amd64

One of my mate found that a github action actually exist for the sql proxy https://github.com/mattes/gce-cloudsql-proxy-action/issues/8 , as you can see, it did use long live credential, but another github action here doesn't : https://github.com/wagnerpereira/gce-cloudsql-proxy-action/tree/v2.0.2

It work great in our CI, but we also realized that the cloud sql proxy advised in the documentation is a totally different binary than the one from the action, this is the url of the sql proxy from the github action we now use : https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy        

I have been trying to understand what was that sql proxy, and found the release page of your repo : https://github.com/GoogleCloudPlatform/cloud-sql-proxy/releases

Here you release both version cloud sql proxy binaries, and both were updated 3 weeks ago from today : 

- cloud-sql-proxy v2.7.0 : https://github.com/GoogleCloudPlatform/cloud-sql-proxy/releases/tag/v2.7.0
- cloud_sql_proxy v1.33.0 : https://github.com/GoogleCloudPlatform/cloud-sql-proxy/releases/tag/v1.33.11

Those difference aren't documented anywhere I could find.

**Comment by enocom** [comment]
In short, cloud_sql_proxy is v1, cloud-sql-proxy is v2. We have a migration guide here: https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/migration-guide.md.

Both versions use the exact same ADC (application default credential) setup. In fact, in our CI tests in this repo, we use the same [google-github-actions/auth@v1](https://github.com/google-github-actions/auth) action to run tests.

If you can share what's working and what's not in terms of action setup, I can help too.

**Comment by kopax-polyconseil** [comment]
> If you can share what's working and what's not in terms of action setup, I can help too.

This is how we tried to open at first, using v2, the proxy : 

```
      - name: Enable cloud SQL proxy to temp instance
        run: |
          curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.7.0/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy
          nohup ./cloud-sql-proxy ${{ env.PRODUCTION_INSTANCE_PROJECT }}:${{ env.TEMP_INSTANCE_REGION }}:${{ env.TEMP_INSTANCE_NAME }} > cloud-sql-proxy.out 2> cloud-sql-proxy.err < /dev/null &
          echo $!
          echo CLOUD_SQL_PROXY_PID=$(echo $!) >> $GITHUB_ENV
```

With this, we were having this error:

```js
$ ./cloud-sql-proxy xxx-metier-prod:europe-west1:rebuild-staging-20231003-597f24
2023/10/03 14:03:31 Authorizing with Application Default Credentials
2023/10/03 14:03:31 could not resolve version for "xxx-metier-prod:europe-west1:rebuild-staging-20231003-597f24": failed to get instance: Refresh error: failed to get instance metadata (connection name = "xxx-metier-prod:europe-west1:rebuild-staging-20231003-597f24"): googleapi: Error 403: Cloud SQL Admin API has not been used in project 977236680937 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sqladmin.googleapis.com/overview?project=977236680937 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.Help",
    "links": [
      {
        "description": "Google developers console API activation",
        "url": "https://console.developers.google.com/apis/api/sqladmin.googleapis.com/overview?project=97723668xxx"
      }
    ]
  },
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "googleapis.com",
    "metadata": {
      "consumer": "projects/97723668xxxx",
      "service": "sqladmin.googleapis.com"
    },
    "reason": "SERVICE_DISABLED"
  }
]
, accessNotConfigured
```

We have replaced it with:

```
      - uses: wagnerpereira/gce-cloudsql-proxy-action@v2
        name: Enable cloud SQL proxy to temp instance
        with:
          instance: ${{ env.PRODUCTION_INSTANCE_PROJECT }}:${{ env.TEMP_INSTANCE_REGION }}:${{ env.TEMP_INSTANCE_NAME }}
```

The code for [wagnerpereira/gce-cloudsql-proxy-action@v2](https://github.com/wagnerpereira/gce-cloudsql-proxy-action/blob/47db8372a6578d9f2a0d355790207611511027b0/action.yml#L30-L53) action is as follow : 

```
    - name: Start Google Cloud SQL Proxy
      shell: bash
      run: |
        # Download Linux binary
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy        
        chmod +x cloud_sql_proxy

        # Start Cloud SQL Proxy
        ./cloud_sql_proxy -instances=${{ inputs.instance }}=tcp:127.0.0.1:${{ inputs.port }} &

        # wait until connections are accepted
        sleep 3
        isready=0
        for i in {1..10}; do
          echo "Wait for connections to be ready ... $i/10"
          (${{ github.action_path }}/wait-for-it.sh --quiet --timeout=3 --host=127.0.0.1 --port=${{ inputs.port }} || exit $?) && true # escape bash's pipefail
          isready=$?
          if [[ $isready -eq 0 ]]; then
            break
          fi
          sleep 2
        done

        # exit with error code if we couldn't connect
        if [[ $isready -ne 0 ]]; then
          exit $isready 
        fi
```


With this proxy worked fine.

Both where preceded by [google-github-actions/auth@v1](https://github.com/google-github-actions/auth) action.

> We have a migration guide here: https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/migration-guide.md.

Thanks, but as you can seem the migration syntax v1 to v2 was not in cause here. Do you have a clue why we had such issue with v2 ?

**Comment by enocom** [comment]
This is definitely a credential setup problem. Can you show me how you're configuring credentials in the step before each action?

**Comment by kopax-polyconseil** [comment]
> This is definitely a credential setup problem. Can you show me how you're configuring credentials in the step before each action?

This is how we perform auth in all our CIs : 


```yml
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.GCP_METIER_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.DATABASE_OPERATIONS_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v1

```

This credentials work fines with v1:

```yml
      - uses: wagnerpereira/gce-cloudsql-proxy-action@v2
        name: Enable cloud SQL proxy to temp instance
        with:
          instance: ${{ env.PRODUCTION_INSTANCE_PROJECT }}:${{ env.TEMP_INSTANCE_REGION }}:${{ env.TEMP_INSTANCE_NAME }}
```

But fail to works with v2:

```yml

      - name: Enable cloud SQL proxy to temp instance
        run: |
          curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.7.0/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy
          nohup ./cloud-sql-proxy ${{ env.PRODUCTION_INSTANCE_PROJECT }}:${{ env.TEMP_INSTANCE_REGION }}:${{ env.TEMP_INSTANCE_NAME }} > cloud-sql-proxy.out 2> cloud-sql-proxy.err < /dev/null &
          echo $!
          echo CLOUD_SQL_PROXY_PID=$(echo $!) >> $GITHUB_ENV
```

**Comment by enocom** [comment]
The Google Auth action will populate `GOOGLE_APPLICATION_CREDENTIALS` which the Proxy picks up (without having to explicitly set them).

**Comment by enocom** [comment]
Going to assume you got it working. If not feel free to re-open and we can help.

**Comment by daaain** [comment]
The YAML linter threw the book at me, this is how it should look like with consistent whitespace, right?

```yaml
      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@35b0e87d162680511bf346c299f71c9c5c379033 # v1.1.1
        with:
          workload_identity_provider: ${{ secrets.PROVIDER_NAME }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@e30db14379863a8c79331b04a9969f4c1e225e0b # v1.1.1
      - id: 'secrets'
        name: Get secrets
        uses: google-github-actions/get-secretmanager-secrets@4d6d3dfd94110800dda8d84109cb6da0f6a5919d # v1.0.1
        with:
          secrets: |-
            POSTGRES_CONNECTION_NAME:${{ secrets.GOOGLE_CLOUD_PROJECT }}/POSTGRES_CONNECTION_NAME
            POSTGRES_USER:${{ secrets.GOOGLE_CLOUD_PROJECT }}/POSTGRES_USER
            POSTGRES_USER_IAM:${{ secrets.GOOGLE_CLOUD_PROJECT }}/POSTGRES_USER_IAM
            POSTGRES_PASS:${{ secrets.GOOGLE_CLOUD_PROJECT }}/POSTGRES_PASS
            POSTGRES_DB:${{ secrets.GOOGLE_CLOUD_PROJECT }}/POSTGRES_DB
      - name: Enable cloud SQL proxy to temp instance
        run: |
          curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.7.0/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy
          nohup ./cloud-sql-proxy ${{ steps.secrets.outputs.POSTGRES_CONNECTION_NAME }} > cloud-sql-proxy.out 2> cloud-sql-proxy.err < /dev/null &
          echo $!
          echo CLOUD_SQL_PROXY_PID=$(echo $!) >> $GITHUB_ENV
      - run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends postgresql-client
      - run: |
          PGPASSWORD=mycoolpassword psql -h 127.0.0.1 -U postgres -c 'SELECT NOW()'
```
