### ISSUE TITLE
Define a Docker health check

### ISSUE THREAD

**Issue by GergelyKalmar** [GoogleCloudPlatform/cloud-sql-proxy#2046]
### Feature Description

I'd like to use Docker Compose's [health checks](https://docs.docker.com/compose/compose-file/05-services/#healthcheck) to bring up the proxy before starting dependent services, but I can't seem to be able to ping the readiness endpoints from within the container image.

It would be awesome if there was a health check defined in the cloud-sql-proxy image itself (see https://docs.docker.com/engine/reference/builder/#healthcheck).

### Alternatives Considered

I tried pinging the existing readiness endpoint:
```
services:
  ...
  cloud_sql_proxy:
    ...
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9999/readiness']
      interval: 3s
      timeout: 3s
      retries: 5
```

However, it seems that `curl` is not available in the Docker image, and neither is any other utility that would allow one to hit the readiness endpoint.
