### ISSUE TITLE
How can I ensure cloud-sql-proxy sidecar container is running before other containers connecting to cloudsql from k8s?

### ISSUE THREAD

**Issue by chardch** [GoogleCloudPlatform/cloud-sql-proxy#2063]
### Question

I have a k8s pod with 2 containers

- cloud-sql-proxy
- a container from third party which connects to my cloudsql private-ip instance

I want the cloud-sql-proxy to start running before the container connecting to my cloudsql instance. I experimented with using `lifecycle.postStart` in the cloud-sql-proxy container spec, but the container image doesn't seem to include any commands I can viably use to ensure other containers start after it. 

This must be a common desired behavior, so is there any suggestion here?

**Comment by jackwotherspoon** [comment]
We recently added support for a `wait` command #2041 and I think it is what you are looking for.

From the description of #2041:

To help ensure the Proxy is up and ready, this commit adds a wait command with an optional `--max` flag to set the maximum time to wait.

By default when invoking this command:

```
./cloud-sql-proxy wait
```

The Proxy will wait up to the maximum time for the /startup endpoint to respond. This command requires that the Proxy be started in another process with the HTTP health check enabled. If an alternate health check port or address is used, as in:

```
./cloud-sql-proxy <INSTANCE_CONNECTION_NAME> \
  --http-address 0.0.0.0 \
  --http-port 9191
```

Then the wait command must also be told to use the same custom values:

```
./cloud-sql-proxy wait \
  --http-address 0.0.0.0 \
  --http-port 9191
```

By default the wait command will wait 30 seconds. To alter this value, use:

```
./cloud-sql-proxy wait --max 10s
```

@chardch does that work for your use-case?

**Comment by enocom** [comment]
This works in combination with a poststart hook. Context: https://medium.com/@marko.luksa/delaying-application-start-until-sidecar-is-ready-2ec2d21a7b74

**Comment by enocom** [comment]
Going to close this. Feel free to reopen if you’re still stuck on this.

**Comment by chardch** [comment]
Got it, thank you for this info! The wait command is exactly what I was looking for.

**Comment by joaoviana** [comment]
> This works in combination with a poststart hook. Context: https://medium.com/@marko.luksa/delaying-application-start-until-sidecar-is-ready-2ec2d21a7b74

Hi @enocom, I was wondering if you could share how it should work with a `postStart` hook and `wait`?

Version: `cloud-sql-proxy:2.11.4`

```yml
lifecycle:                                                                                                                                                                                                     
   postStart:                                                                                                                                                                                                        
     exec:                                                                                                                                                                                                      
       command:                                                                                                                                                                                                 
            - /bin/sh          
            - -c                                                                                                                                                                                                     
            - ./cloud-sql-proxy wait --http-address 0.0.0.0 --http-port XXXX   
```

and I set the right envs (I believe): 

```yml
  env:                                                                                                                                                                                                           │                                                                                                                                                                                           │
│     - name: CSQL_PROXY_HEALTH_CHECK                                                                                                                                                                                │
│       value: "true"                                                                                                                                                                                                │
│     - name: CSQL_PROXY_HTTP_PORT                                                                                                                                                                                   │
│       value: "XXXX"                                                                                                                                                                                                │
│     - name: CSQL_PROXY_HTTP_ADDRESS                                                                                                                                                                                │
│       value: 0.0.0.0                                                                                                                                                                                               │
│     - name: CSQL_PROXY_EXIT_ZERO_ON_SIGTERM                                                                                                                                                                        │
│       value: "true"                                                                                                                                                                                                │
│     - name: CSQL_PROXY_STRUCTURED_LOGS                                                                                                                                                                             │
│       value: "true"                 
```

And I keep getting a ` PostStartHook failed` error. 
I also grabbed the `startupProbe` and `livenessProbe` from the `healthcheck` examples, and added them to my set up.

Thanks 😃
