### ISSUE TITLE
Cloud SQL Proxy have support GKE sidecar with replication or not?

### ISSUE THREAD

**Issue by ALTELMA** [GoogleCloudPlatform/cloud-sql-proxy#2075]
### Question

How can I use a cloud proxy to connect with both instances between master and slave? I tried to find the document on this but was not found. Can anyone help me with this?

### Code

```
- name: cloudsql-proxy
  image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8-alpine
  args:
     - "myproject:us-central1:myprimary?port=5000 myproject:us-central1:myprimary?port=5001"
     - "credential_file=/secrets/cloudsql/credentials.json"
  securityContext:
    runAsUser: 2
    allowPrivilegeEscalation: false
  volumeMounts:
    - name: credential-volume
      mountPath: /secrets/cloudsql
      readOnly: true
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "2Gi"
      cpu: "1"
```
