### ISSUE TITLE
Unable to connect to GCP SQL when using --private-ip flag

### ISSUE THREAD

**Issue by mudasirmirza** [GoogleCloudPlatform/cloud-sql-proxy#2316]
### Question

When using Cloud SQL Proxy with the `--private-ip` flag to connect a MySQL instance hosted in a private IP setup, the connection fails inside a GKE pod. Without the `--private-ip` flag, the proxy works fine over a public IP, but the private IP configuration fails to function as expected.

The setup uses:

1. A GKE cluster in VPC A with VPC peering to the default VPC (where the Cloud SQL instance is accessible).
2. MySQL is configured to run on port 3306 with Private IP in default VPC
3. The Cloud SQL Proxy is deployed in the same pod as a MySQL client to handle local connections in the GKE cluster running in VPC A
4. Everything is in the same project

Logs when using `--private-ip`, for some reason, it connects to port 3307
```
❯ kubectl logs ubuntu-pod-cloud-sql -c cloud-sql-proxy -f
{"severity":"INFO","timestamp":"2024-10-28T11:35:09.344Z","message":"Authorizing with Application Default Credentials"}
{"severity":"INFO","timestamp":"2024-10-28T11:35:09.391Z","message":"[project:region:instance_id] Listening on [::]:3306"}
{"severity":"INFO","timestamp":"2024-10-28T11:35:09.391Z","message":"The proxy has started successfully and is ready for new connections!"}
{"severity":"INFO","timestamp":"2024-10-28T11:35:09.391Z","message":"Enabling pprof endpoints at localhost:9091"}
{"severity":"INFO","timestamp":"2024-10-28T11:36:10.807Z","message":"[project:region:instance_id] accepted connection from 127.0.0.1:60080"}
{"severity":"ERROR","timestamp":"2024-10-28T11:36:40.807Z","message":"[project:region:instance_id] failed to connect to instance: Dial error: failed to dial (connection name = \"project:region:instance_id\"): dial tcp 10.128.192.7:3307: i/o timeout"}
```

Below is the YAML manifest used to create the POD
```
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod-cloud-sql
  namespace: default
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/bash"]
    args: ["-c", "apt-get update && apt-get install -y mysql-client && sleep infinity"]
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    volumeMounts:
      - name: service-account
        mountPath: /secrets/
        readOnly: true

  - name: cloud-sql-proxy
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.4
    args:
      - "--private-ip"
      - "--structured-logs"
      - "--debug"
      - "--port=3306"
      - "--address=0.0.0.0"
      - "project_id:region:instance_id"
      - "--credentials-file=/secrets/key.json"
    securityContext:
      runAsNonRoot: true
    volumeMounts:
      - name: service-account
        mountPath: /secrets/
        readOnly: true

  volumes:
  - name: service-account
    secret:
      secretName: cloud-sql-sa-key
```

GCP SQL instances is currently configured to use "Public IP" and "Private IP" and there is a list of IPs in the "authorized networks" which has the IP from which the call is being made.

Expected Behavior:
* The Cloud SQL Proxy should allow connections from the pod to the MySQL instance using private IP over port 3306

1. VPC Peering has been established between VPC A and default VPC
2. A valid firewall rule also present on the default VPC to allow IP range of VPC A

After doing all this, I am stuck and unable to make the connection.
